# Searchable Grails 2.x Plugin
:toc: left
:language: asciidoc
:theme: html5
:source-highlighter: highlight.js
:icons: font

:leveloffset: 1

# Summary

Adds rich search functionality to Grails domain models. Built on Compass (http://www.compass-project.org/) and Lucene (http://lucene.apache.org/) This version is recommended for JDK 1.5+

# Installation

Use the above dependency declaration in your BuildConfig.groovy file and then add

----
mavenRepo "http://repo.grails.org/grails/core"
----

to the repositories section of that file.

# Description

The Searchable Plugin brings rich search features to Grails applications with minimum effort, and gives you power and flexibility when you need it.

It is built on the fantastic Compass Search Engine Framework and Lucene and has the same license as Grails (Apache 2).

The roadmap and issues are tracked in JIRA.

WARNING: Only versions 0.6.5+ work with Grails 2.3+.

WARNING: Only versions 0.6.4+ work with Grails 2.2+.

Initially the plugin will focus on exposing Groovy domain models.

Support for Java domain classes is on the roadmap but until then, if your Grails application uses Java domain classes, using Compass's native annotations or XML mapping config and setting up Compass yourself may be a better fit at this stage.

# Features

* Maps searchable domain classes to the underlying search index
* Performs a bulk index of all searchable class instances in the database
* Automatically synchronises any changes made through GORM/hibernate with the index
* Provides a SearchableService for easy cross-domain-class searching and index management
* Adds domain class methods for easy per-domain-class searching and index management
* Provides a SearchableController and view for testing queries and demonstrating the Searchable Plugin API
* Follows a Convention over Configuration approach with overridable behaviour where necessary

include::quick_start.adoc[]

include::searchablecontroller_and_view.adoc[]

include::searching.adoc[]

:leveloffset: 2

include::searching_query_strings.adoc[]

include::searching_query_builder.adoc[]

include::searching_sorting.adoc[]

:leveloffset: 1

include::mapping.adoc[]

:leveloffset: 2

include::mapping_not_all_properties.adoc[]

include::mapping_conventions.adoc[]

include::mapping_compass_concepts.adoc[]

include::mapping_mapping_dsl.adoc[]

include::mapping_class_property_mapping.adoc[]

include::mapping_searchable_id.adoc[]

include::mapping_searchable_property.adoc[]

include::mapping_searchable_reference.adoc[]

include::mapping_searchable_component.adoc[]

include::mapping_class_mapping.adoc[]

include::mapping_compass_annotations.adoc[]

include::mapping_compass_xml.adoc[]

:leveloffset: 1

include::managing_the_index.adoc[]

include::configuration.adoc[]

include::analyzers.adoc[]

include::converters.adoc[]

include::debugging.adoc[]

include::faq.adoc[]

include::methods.adoc[]

:leveloffset: 2

include::methods_search.adoc[]

include::methods_counthits.adoc[]

include::methods_morelikethis.adoc[]

include::methods_suggestquery.adoc[]

include::methods_termfreqs.adoc[]

include::methods_index.adoc[]

include::methods_unindex.adoc[]

include::methods_reindex.adoc[]

include::methods_rebuildspellingsuggestions.adoc[]

include::methods_startmirroring.adoc[]

include::methods_stopmirroring.adoc[]

:leveloffset: 1

include::releases.adoc[]

:leveloffset: 0

