= Mapping

A searchable class mapping describes how the class instance appears in the index and the data is searched.

This includes things like:

* Which properties are searchable
* How a property is processed during indexing - whether it is "analyzed" or not, for example
* How a property influences the search - whether it has a "boost", for example
* How associated searchable classes are linked and/or embed one another's searchable data

When you declare

----
static searchable = true
----

the plugin maps the class with
built-in link:index.html#_mapping_conventions[conventions].

You can override these conventions in a number of ways:

[discrete]
== The Mapping DSL

The link:index.html#_mapping_dsl[mapping DSL], is a bit like GORM's mapping DSL.

You can selectively override the built-in link:index.html#_mapping_conventions[conventions] for specific properties (or the class itself),
and inherit the default behaviour for any properties you do no explicitly map.

[discrete]
== Native Compass Mappings

You can also use link:index.html#_mapping_compass_annotations[Compass annotations] and
link:index.html#_mapping_compass_xml[Compass XML] to map your classes.

With either link:index.html#_mapping_compass_xml[Compass XML] or
link:index.html#_mapping_compass_annotations[Compass annotations],
you need to map every aspect of the searchable class yourself. In other words,
the built-in link:index.html#_mapping_conventions[conventions] no longer apply to classes you map with Compass mappings.