= Searchable Reference

[discrete]
== Summary

Used to map [searchable references|Searchable Plugin - Mapping - Compass concepts#Searchable Reference].

[discrete]
== Syntax

----
static searchable = {
    propertyName options
}
----

----
static searchable = {
    propertyName reference: true
}
----

----
static searchable = {
    propertyName reference: options
}
----

[discrete]
== Description

Maps the class's `propertyName` property with the given [options|#Options].

You can use all three syntaxes when a [conventional mapping|Searchable Plugin - Mapping - Conventions] would give you a [searchable reference|Searchable Plugin - Mapping - Compass concepts#Searchable Reference].

When you want to change a [conventional searchable component mapping|Searchable Plugin - Mapping - Conventions] (which can happen when the associated class is embedded), you can use either of the last two syntaxes to make it a [searchable reference|Searchable Plugin - Mapping - Compass concepts#Searchable Reference] instead.

[discrete]
== Parameters

* *`options`* - a `Map` of [options|#Options]

[discrete]
=== Options

* *`accessor`* - How the property is accessed. One of `"field"` or `"property"`. Default is `"property"`
* *`cascade`* - The operations to cascade to the target association. A `String` comma-delimited-list of values in `"all"`, `"create"`, `"save"` and `"delete"`.
* *`converter`* - The name of a configured converter to use to convert the property value to/from text
* *`lazy`* - If `true` the association is lazy when recreating the owing instance for search results. Only applicable to Collections or arrays. Default is `false`

[discrete]
== Examples

----
// Provide a custom converter
metadata converter: "metadata\_converter"
----

----
// Map metadata as a reference, overriding any conventional mapping
metadata reference: true
----

----
// Map metadata as a reference, overriding any conventional mapping
// and define some options
metadata reference: [converter: "metadata\_converter"]
----