= unindex

[discrete]
== Summary

Un-indexes searchable class instances (removes them from the search index)

[discrete]
== Syntax

----
domainObject.unindex()
----

----
DomainClass.unindex()
DomainClass.unindex(DomainClass instances...)
DomainClass.unindex(Serializable ids...)
----

----
searchableService.unindex()
searchableService.unindex(Map options)
searchableService.unindex(DomainClass instances...)
searchableService.unindex(Serializable ids..)
searchableService.unindex(Map options, Serializable ids...)
----

[discrete]
== Description

When called as a domain class instance method, un-indexes the instance.

When called as a domain class static method with no arguments, un-indexes all instances for that class (or hierarchy).

When called as a `SearchableService` method with no arguments, un-indexes all searchable class instances.

In other invocations, un-indexes the searchable class instances you provide or identify.

[discrete]
== Parameters

* *`instances`* - One or more searchable class instances
* *`ids`* - One or more searchable class instance ids
* *`options`* - A `Map` of [options|Searchable Plugin - Methods - unindex#options]

[discrete]
=== options

* *`class`* - a searchable class; use this option with the `SearchableService` method and `ids` parameter or as an alternative to the domain-class method

[discrete]
== Returns

No meaningful value

[discrete]
== Examples

----
// Unindex a Post instance
post.unindex()
----

----
// Add some Menus to the index
Menu.unindex(m1, m2)
----

----
// Add all Countries to the index
Country.unindex()
----

----
// Unindex everything
searchableService.unindex()
----

----
// Unindex the identified Book
searchableService.unindex(class: Book, 1l)
----

----
// Unindex the given Tool
searchableService.unindex(tool)
----



